export const metadata = {
  title: "OneKeymap Privacy Policy",
  description: "How OneKeymap handles telemetry, local data, and your privacy choices.",
};

const sections = [
  {
    title: "What this policy covers",
    body: [
      "OneKeymap is a native macOS application designed to keep your editor shortcuts in sync. This policy explains what data we collect, how we use it, and the choices available to you.",
      "By using OneKeymap you agree to the practices described below. If you disagree with this policy, please uninstall the app and discontinue use.",
    ],
  },
  {
    title: "Local configuration data",
    body: [
      "Your keymap configurations, editor paths, and any files generated by OneKeymap remain on your Mac. We never transmit or store these files outside of your device.",
      "We strongly recommend keeping backups of your editor configuration files. Although OneKeymap offers diff previews, you are responsible for safeguarding your data.",
    ],
  },
  {
    title: "Anonymous usage analytics",
    body: [
      "To improve stability and prioritize new features we collect anonymous, aggregated telemetry using OpenTelemetry.",
      "Usage signals include high-level feature events (for example, how often the sync button is clicked) and performance metrics. We do not capture keymap contents, file paths, IP addresses, or any other personally identifying information.",
      "Telemetry is anonymized before it leaves your device and cannot be traced back to a specific individual.",
      "You can disable analytics at any time from the app preferences. When disabled, OneKeymap stops sending telemetry immediately.",
    ],
  },
  {
    title: "Crash and error reporting",
    body: [
      "If OneKeymap encounters an unexpected error, we may submit a minimal crash report containing stack traces and build metadata to help troubleshoot issues.",
      "Crash reports exclude keymap contents and editor configuration data. You can opt out of automatic crash submission in the same preferences panel as telemetry.",
    ],
  },
  {
    title: "Third-party services",
    body: [
      "We rely on trusted infrastructure providers to deliver product analytics. These providers are bound by agreements that restrict the use of any telemetry to operating and improving OneKeymap.",
      "We do not sell or rent your data and we do not share analytics with advertisers.",
    ],
  },
  {
    title: "Children's privacy",
    body: [
      "OneKeymap is not directed at children under 13. If you believe a child provided personal data to us, please contact us so we can delete the information.",
    ],
  },
  {
    title: "Changes to this policy",
    body: [
      "We may update this policy to reflect product improvements or legal requirements. When we do, we will update the \"Last updated\" date at the top of the page and surface the change in-app.",
      "Continued use of OneKeymap after the policy change constitutes acceptance of the revised policy.",
    ],
  },
  {
    title: "Contact",
    body: [
      "Questions about this policy? Email us at support@onekeymap.com.",
    ],
  },
];

export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-4xl px-4 pb-20 pt-32 sm:px-6 lg:px-8">
      <header className="text-center">
        <p className="text-sm uppercase tracking-wide text-blue-500">Last updated: 23 September 2025</p>
        <h1 className="mt-4 text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl">
          OneKeymap Privacy Policy
        </h1>
        <p className="mt-4 text-lg text-gray-600">
          Learn how OneKeymap protects your privacy while keeping your shortcuts synchronized across editors.
        </p>
      </header>

      <section className="mt-16 space-y-12">
        {sections.map((section) => (
          <article key={section.title} className="rounded-3xl bg-white p-8 shadow-xl ring-1 ring-gray-100">
            <h2 className="text-2xl font-semibold text-gray-900">{section.title}</h2>
            <ul className="mt-6 space-y-3 text-base text-gray-600">
              {section.body.map((paragraph) => (
                <li key={paragraph} className="flex items-start gap-3">
                  <span className="mt-1 h-2.5 w-2.5 flex-none rounded-full bg-blue-500" />
                  <span>{paragraph}</span>
                </li>
              ))}
            </ul>
          </article>
        ))}
      </section>
    </main>
  );
}
